# https://taskfile.dev

version: "3"

vars:
  REPOSITORY: ghcr.io/adrianliechti/wingman-segmenter

tasks:
  run:
    cmds:
      - docker run -it --rm --pull always -p 8000:8000 {{.REPOSITORY}}

  publish:
    cmds:
      - docker buildx build . --no-cache --push --platform linux/amd64,linux/arm64 --tag {{.REPOSITORY}}:latest