# https://taskfile.dev

version: "3"

vars:
  REPOSITORY: ghcr.io/adrianliechti/wingman-segmenter

tasks:
  run:
    cmds:
      - docker run -it --rm --pull always -p 50051:50051 {{.REPOSITORY}}
  
  generate:
    cmds:
      - ./.venv/bin/python -m grpc_tools.protoc -I. --python_out=. --pyi_out=. --grpc_python_out=. segmenter.proto

  publish:
    cmds:
      - docker buildx build . --no-cache --push --platform linux/amd64,linux/arm64 --tag {{.REPOSITORY}}:latest